pages:
  script:
    - mkdir .public
    - cp -r ./docs .public/docs
    - cp -r ./icon.png .public/icon.png
    - cp -r ./CONTRIBUTING.md .public/CONTRIBUTING.md
    - cp -r ./index.html .public/index.html
    - cp -r ./LICENSE.md .public/LICENSE.md
    - cp -r ./README.md .public/README.md
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
