---
name: powered-reverse-proxy-docs-dev

services:
  powered-reverse-proxy-docs-dev:
    container_name: powered-reverse-proxy-docs-dev
    image: powered-reverse-proxy-docs:latest-dev
    build:
      context: ..
      dockerfile: ./docsify/Dockerfile.dev
    volumes:
    - ../docs:/app/docs
    - ../icon.png:/app/icon.png
    - ../CONTRIBUTING.md:/app/CONTRIBUTING.md
    - ../index.html:/app/index.html
    - ../LICENSE.md:/app/LICENSE.md
    - ../README.md:/app/README.md
    ports:
    - 3000:3000
    restart: unless-stopped
