---
name: traefik-standalone

networks:
  traefik-net:
    name: traefik-net

volumes:
  traefik-acme:
    name: traefik-acme

services:
  traefik-standalone:
    container_name: traefik-standalone
    image: ${TRAEFIK_IMG}:${TRAEFIK_IMG_VERSION}
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - CF_DNS_API_TOKEN=${TRAEFIK_CF_DNS_API_TOKEN}
      - CF_ZONE_API_TOKEN=${TRAEFIK_CF_ZONE_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - traefik_acme:/acme_data:rw
      - ./data:/etc/traefik:rw
    networks:
      - proxy_net
    ports:
      - ${TRAEFIK_PORT_HTTP}:${TRAEFIK_PORT_HTTP}
      - ${TRAEFIK_PORT_HTTPS}:${TRAEFIK_PORT_HTTPS}
    restart: always
